
import FreeCAD as App # type: ignore



#------------------------------------------------------------
def rmv(doc_name, obj_name):
    doc = App.getDocument(doc_name)
    doc.removeObject(obj_name)
    doc.recompute()
    pass


#------------------------------------------------------------


#------------------------------------------------------------


#------------------------------------------------------------


#------------------------------------------------------------


#------------------------------------------------------------


#------------------------------------------------------------
